// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CasusBlok4.Migrations
{
    [DbContext(typeof(ProductRegistratieContext))]
    [Migration("20210529101757_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("CasusBlok4.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("CasusBlok4.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<short?>("PointsWorth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubCategorieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("SubCategorieId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CasusBlok4.Models.SubCategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeadCategorie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("SubCategorie");
                });

            modelBuilder.Entity("CasusBlok4.Models.Product", b =>
                {
                    b.HasOne("CasusBlok4.Models.Categorie", "Categorie")
                        .WithMany("Products")
                        .HasForeignKey("CategorieId");

                    b.HasOne("CasusBlok4.Models.SubCategorie", "SubCategorie")
                        .WithMany("Products")
                        .HasForeignKey("SubCategorieId");

                    b.Navigation("Categorie");

                    b.Navigation("SubCategorie");
                });

            modelBuilder.Entity("CasusBlok4.Models.SubCategorie", b =>
                {
                    b.HasOne("CasusBlok4.Models.Categorie", "Categorie")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategorieId");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("CasusBlok4.Models.Categorie", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("CasusBlok4.Models.SubCategorie", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
